# The wherever server, built from source.
#
# This is a PLAIN FUNCTION OF `pkgs`, deliberately NOT a flake output, and it is
# the interface consumers are expected to use:
#
#     import ./services/wherever/package.nix { pkgs = <the nixpkgs THEY chose>; }
#
# A consumer that evaluates several nixpkgs pins must be able to build this
# against one of ITS pins. Taking the package from `wherever`'s own flake would
# drag a third nixpkgs into that consumer's closure, which is exactly what a
# multi-pin deployment repo avoids. So `flake.nix` here is a thin convenience
# wrapper that calls THIS file; the file itself never mentions flakes, inputs, or
# a locked nixpkgs. See docs/adr/0008-nix-packaging-package-nix-is-the-interface-flake-is-a-wrapper.md.
#
# Regenerating `pnpmDepsHash`: it pins the CONTENT of the resolved dependency
# set, so it MUST be regenerated whenever `pnpm-lock.yaml` changes. Run
# `./nix/update-pnpm-deps-hash.sh` (or `nix run .#update-pnpm-deps-hash`), which
# rewrites the value below. `nix/check-pnpm-deps-hash.sh` is the CI-side guard:
# it fails loudly when the hash is stale, rather than letting a build silently
# succeed against the dependency set of an older lockfile.
{
  pkgs,
  lib ? pkgs.lib,
  # Pinned MAJOR versions rather than `pkgs.nodejs` / `pkgs.pnpm`: the consumer
  # picks the nixpkgs, but the toolchain a given source tree builds under is a
  # property of THIS repo (the lockfile is `lockfileVersion: 9.0`, which pnpm 11
  # rewrites). Both are still overridable by a consumer that knows better.
  nodejs ? pkgs.nodejs_24,
  pnpm ? pkgs.pnpm_10,
  # The dependency-set hash. Overridable so a consumer tracking an unreleased
  # rev can supply its own without patching this file.
  pnpmDepsHash ? "sha256-lsyonvPm4b3X+DrZPoIbTYMCEyOUsgPX4O7VelmrxSY=",
  # Build id surfaced by the dashboard and the `connected` WS message. A flake
  # passes the git rev; a bare `import` gets the package version.
  buildVersion ? null,
}:

let
  serverPackageJson = lib.importJSON ./server/package.json;
  version = serverPackageJson.version;

  # The consumer chooses the nixpkgs, so this must work across pins. The
  # top-level `pnpmConfigHook` / `fetchPnpmDeps` are the current spelling;
  # `pnpm.configHook` / `pnpm.fetchDeps` are the older (now deprecation-warning)
  # attributes. Prefer the new names, fall back to the old ones.
  pnpmConfigHook = pkgs.pnpmConfigHook or pnpm.configHook;
  fetchPnpmDeps = pkgs.fetchPnpmDeps or pnpm.fetchDeps;

  # An ALLOWLIST of what the build actually reads, not a denylist of what to skip.
  #
  # A denylist is wrong here because this derivation is imported by PATH as well
  # as evaluated through the flake. The flake path only ever sees git-tracked
  # files, but `import ./package.nix { pkgs = ... }` against a working checkout
  # sees EVERYTHING, including this repo's gitignored scratch (`tmp/` and
  # `.kilo/` are ~160 MB between them). That would be copied into the store on
  # every consumer build and on every run of the hash scripts, and it would make
  # the two paths produce different store paths. An allowlist also cannot rot:
  # a new scratch directory is excluded by default rather than by remembering.
  #
  # Top level = the six pnpm workspace members (every one of their package.json
  # files must exist for `--frozen-lockfile` to resolve, even the ones this
  # package does not build), the build orchestration, and the root manifests.
  topLevelAllowed = [
    "client"
    "extension"
    "scripts"
    "server"
    "site"
    "vscode"
    "web"
    "package.json"
    "pnpm-lock.yaml"
    "pnpm-workspace.yaml"
  ];

  # Pruned INSIDE the allowed trees: dependency and build output directories that
  # exist in a working checkout and are regenerated by the build anyway.
  prunedAnywhere = [
    "node_modules"
    ".svelte-kit"
    "dist"
    "build"
    "public"
  ];

  # Exact paths that are GENERATED but gitignored, so they are present in a
  # working checkout and absent in a clean clone. Pruning them keeps the two
  # producing the same store path; the build regenerates this one with `pwag`.
  prunedPaths = [ "web/static/pwa" ];

  src = lib.cleanSourceWith {
    src = ./.;
    name = "wherever-source";
    filter =
      path: type:
      let
        relative = lib.removePrefix (toString ./. + "/") (toString path);
        segments = lib.splitString "/" relative;
        top = builtins.head segments;
      in
      # Top level: allowlist. Deeper: keep everything except the pruned dirs.
      if builtins.length segments == 1 then
        builtins.elem top topLevelAllowed
      else
        !(
          builtins.elem relative prunedPaths
          || (type == "directory" && builtins.elem (baseNameOf path) prunedAnywhere)
        );
  };
in
pkgs.stdenv.mkDerivation (finalAttrs: {
  pname = "wherever";
  inherit version src;

  nativeBuildInputs = [
    nodejs
    pnpm
    pnpmConfigHook
    pkgs.makeWrapper
  ];

  pnpmDeps = fetchPnpmDeps {
    inherit (finalAttrs) pname version src;
    inherit pnpm;
    fetcherVersion = 4;
    hash = pnpmDepsHash;
  };

  # `openssl` is invoked BY NAME at runtime, and only to mint the self-signed
  # certificate the server falls back to when no --ssl-key/--ssl-cert is given.
  # What actually puts it on the server's PATH is the `makeWrapper --prefix PATH`
  # in installPhase, NOT a buildInputs entry, because a systemd unit inherits no
  # login-shell PATH (the whole reason this package exists).

  # The `!= ""` half matters: web/svelte.config.js treats an empty value as
  # absent and falls back to `git rev-parse`, which in the sandbox has neither
  # git nor a .git dir, landing on `timestamp_${Date.now()}` -- a silently
  # non-reproducible build. Fall back to the package version instead.
  env.WHEREVER_BUILD_VERSION =
    if buildVersion != null && buildVersion != "" then buildVersion else "v${version}";

  buildPhase = ''
    runHook preBuild

    # `pnpmConfigHook` installs with --ignore-scripts (correctly: lifecycle
    # scripts are arbitrary code and the root one is `npx only-allow pnpm`,
    # which would need the network). The web app's `prepare` script is a real
    # build step though, so run exactly it, explicitly:
    #   pwag           -> generates the PWA icon set + manifest into static/pwa
    #                     (gitignored, so it is NOT in src and must be produced)
    #   svelte-kit sync -> generates .svelte-kit/tsconfig.json + $types
    pushd web
    ./node_modules/.bin/pwag static/logo.svg src/web-config.json
    ./node_modules/.bin/svelte-kit sync
    popd

    # `@wherever-dev/client` is a WORKSPACE dependency of the web app, and its
    # package.json resolves through `main: dist/index.js` -- a build output that
    # is gitignored. `scripts/build.js` does not build it (the root `build:all`
    # script is what does, ahead of everything else), so without this the web
    # build fails with "Failed to resolve entry for package
    # @wherever-dev/client" on any tree that has not been built by hand first.
    pnpm --filter ./client build

    # The repo's own build orchestration: web -> server/public -> tsc.
    # Called directly rather than through `pnpm build` so a failure points at
    # the step that failed instead of at pnpm.
    node scripts/build.js

    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    # A self-contained, symlink-free production tree for the server package
    # alone. `--frozen-lockfile` is what makes this work offline: without it
    # `deploy` re-RESOLVES the workspace against the npm registry (it choked on
    # the extension's `*` range), which the sandbox has no route to and which
    # would defeat the lockfile anyway.
    # `inject-workspace-packages` is set HERE, in the environment, rather than in
    # the repo's pnpm-workspace.yaml: it is what `deploy` needs to use the SHARED
    # workspace lockfile (its `--legacy` path instead re-RESOLVES every workspace
    # project against the npm registry, which the sandbox has no route to and
    # which chokes on the extension's `*` range). The server has no workspace
    # dependencies, so injection changes nothing about what is produced -- and
    # forcing the setting on the repo would change every developer's install.
    # CI=true both suppresses pnpm's non-TTY confirmation prompt and makes
    # `--frozen-lockfile` the default, which is what keeps this offline.
    CI=true npm_config_inject_workspace_packages=true \
      pnpm --filter=wherever-dev deploy --prod --offline "$out/lib/wherever"

    mkdir -p "$out/bin"

    test -f "$out/lib/wherever/dist/index.js" || { echo "server build output missing"; exit 1; }
    test -f "$out/lib/wherever/public/index.html" || { echo "web build output missing"; exit 1; }

    makeWrapper ${lib.getExe nodejs} "$out/bin/wherever" \
      --add-flags "$out/lib/wherever/dist/index.js" \
      --prefix PATH : ${lib.makeBinPath [ pkgs.openssl ]}

    runHook postInstall
  '';

  # A smoke test that the thing actually RUNS, not just that it linked: `version`
  # boots the real entry point, which fails if a runtime dependency was pruned.
  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    "$out/bin/wherever" --version
    runHook postInstallCheck
  '';

  passthru = {
    inherit nodejs pnpm pnpmDepsHash;
  };

  meta = {
    description = "Standalone multi-session server for the pi coding agent";
    homepage = "https://github.com/wighawag/wherever";
    license = lib.licenses.agpl3Only;
    mainProgram = "wherever";
    platforms = lib.platforms.unix;
  };
})
