#!/bin/sh
# pisearch installer - shell-agnostic.
#
# Installs a `pisearch` command that cd's into the search folder configured in
# ~/.wherever/config.json and launches pi with the web-search skill preloaded.
#
# It installs a small launcher to ~/.local/bin/pisearch (POSIX sh, runnable from
# any shell) and, only if ~/.local/bin is not already on PATH, adds a clearly
# MARKED block to the detected shell rc. Re-running is safe (idempotent).
#
# Usage:
#   sh scripts/pisearch/install.sh
#
# Remove with:
#   sh scripts/pisearch/uninstall.sh
# (manual removal instructions are printed at the end too).

set -eu

MARK_BEGIN="# >>> pisearch >>>"
MARK_END="# <<< pisearch <<<"

# --- Resolve this script's directory, then the web-search skill dir ---
SCRIPT_PATH=$0
case "$SCRIPT_PATH" in
  /*) ABS_SCRIPT=$SCRIPT_PATH ;;
  *)  ABS_SCRIPT=$(pwd)/$SCRIPT_PATH ;;
esac
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$ABS_SCRIPT")" && pwd)
# scripts/pisearch -> repo root is two levels up.
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
SKILL_DIR="$REPO_ROOT/skills/web-search"

if [ ! -f "$SKILL_DIR/SKILL.md" ]; then
  echo "ERROR: web-search skill not found at: $SKILL_DIR" >&2
  echo "Run this installer from inside the wherever repo." >&2
  exit 1
fi

# --- Sanity checks ---
if ! command -v pi >/dev/null 2>&1; then
  echo "WARNING: 'pi' is not on PATH right now. pisearch will still be installed," >&2
  echo "         but it will only work once 'pi' is available." >&2
fi

BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/pisearch"
mkdir -p "$BIN_DIR"

# --- Write the launcher ---
# The launcher reads the search folder from ~/.wherever/config.json at runtime
# (so changing the config does not require reinstalling). Tilde is expanded.
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/bin/sh
# pisearch launcher (generated by scripts/pisearch/install.sh). Do not edit;
# re-run the installer to regenerate.
set -eu

SKILL_DIR="$SKILL_DIR"
CONFIG="\$HOME/.wherever/config.json"

if [ ! -f "\$CONFIG" ]; then
  echo "pisearch: no config at \$CONFIG. Set 'searchFolder' there first." >&2
  exit 1
fi

# Extract searchFolder using jq if available, else python3, else grep/sed.
FOLDER=""
if command -v jq >/dev/null 2>&1; then
  FOLDER=\$(jq -r '.searchFolder // empty' "\$CONFIG" 2>/dev/null || true)
elif command -v python3 >/dev/null 2>&1; then
  FOLDER=\$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1])).get("searchFolder") or "")' "\$CONFIG" 2>/dev/null || true)
else
  FOLDER=\$(grep -o '"searchFolder"[[:space:]]*:[[:space:]]*"[^"]*"' "\$CONFIG" 2>/dev/null | sed 's/.*"searchFolder"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/' || true)
fi

if [ -z "\$FOLDER" ]; then
  echo "pisearch: 'searchFolder' is not set in \$CONFIG." >&2
  echo "Add it, e.g.:  \"searchFolder\": \"~/dev/github/wighawag/pi-search\"" >&2
  exit 1
fi

# Expand a leading ~ to \$HOME.
case "\$FOLDER" in
  "~") FOLDER="\$HOME" ;;
  "~/"*) FOLDER="\$HOME/\${FOLDER#~/}" ;;
esac

mkdir -p "\$FOLDER"
cd "\$FOLDER"

exec pi --skill "\$SKILL_DIR" "\$@"
LAUNCHER_EOF
chmod +x "$LAUNCHER"
echo "Installed launcher: $LAUNCHER"

# --- Ensure ~/.local/bin is on PATH via the detected shell rc ---
add_path_block() {
  rc=$1
  syntax=$2 # "posix" or "fish"
  [ -f "$rc" ] || : > "$rc"
  if grep -qF "$MARK_BEGIN" "$rc" 2>/dev/null; then
    echo "PATH block already present in: $rc (left as-is)"
    return
  fi
  {
    printf '\n%s\n' "$MARK_BEGIN"
    if [ "$syntax" = "fish" ]; then
      printf 'if not contains %s/.local/bin $PATH\n    set -gx PATH %s/.local/bin $PATH\nend\n' "$HOME" "$HOME"
    else
      printf 'case ":$PATH:" in *":$HOME/.local/bin:"*) ;; *) PATH="$HOME/.local/bin:$PATH" ;; esac\n'
    fi
    printf '%s\n' "$MARK_END"
  } >> "$rc"
  echo "Added PATH block to: $rc"
}

# Is ~/.local/bin already on PATH?
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ON_PATH=1 ;;
  *) ON_PATH=0 ;;
esac

if [ "$ON_PATH" -eq 1 ]; then
  echo "$BIN_DIR already on PATH; no rc changes needed."
else
  SHELL_NAME=$(basename "${SHELL:-sh}")
  case "$SHELL_NAME" in
    fish)
      add_path_block "$HOME/.config/fish/config.fish" fish
      ;;
    zsh)
      add_path_block "${ZDOTDIR:-$HOME}/.zshrc" posix
      ;;
    bash)
      if [ -f "$HOME/.bashrc" ]; then
        add_path_block "$HOME/.bashrc" posix
      else
        add_path_block "$HOME/.bash_profile" posix
      fi
      ;;
    *)
      add_path_block "$HOME/.profile" posix
      ;;
  esac
  echo "Open a new terminal (or source your rc) to pick up PATH."
fi

cat <<INFO

Done. Use it with:
  pisearch                 # opens pi in the search folder, web-search skill on
  pisearch "your question" # (extra args are passed through to pi)

To remove:
  sh "$SCRIPT_DIR/uninstall.sh"
or manually:
  - delete $LAUNCHER
  - remove the block between '$MARK_BEGIN' and '$MARK_END' from your shell rc
INFO
